# example netlify.toml
[build]
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  from = "https://bites-restaurant-plf.netlify.app/menu"
  to = "https://bites-restaurant.herokuapp.com/menu"
  status = 200
